import type { Metadata } from "next";
import React from "react";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";
import { Button } from "@repo/ui/button";
import { BUILD_ID_FILE } from "next/dist/shared/lib/constants";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
            <Button className="my-button" href="/">Home</Button>
            <Button className="my-button" href="/courses">Courses</Button>
            <Button className="my-button" href="/assignments">Assignments</Button>
            <Button className="my-button" href="/grades">Grades</Button>
        {children}
      </body>
    </html>
  );
}
